# Generated by Django 6.0.8 on 2026-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AINavigator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'AI Navigator',
                'verbose_name_plural': 'AI Navigator',
                'permissions': (('use_read', 'Use AI Navigator in read-only mode'), ('use_write', 'Use AI Navigator with write capabilities')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
